const events = [
    {
        id: 122,
        title: 'Welcoming new dev 🍻',
        event_start: new Date('2019/10/01 19:00:00').getTime(),
        event_end: new Date('2019/10/01 22:00:00').getTime(),
        image_url: 'https://d24wuq6o951i2g.cloudfront.net/img/events/splash/front-end-test-beer.jpg',
        venue: {
            name: 'Splash Madrid',
            address: 'Carrera de San Jerónimo 18',
            city: 'Madrid',
            postalCode: 28014,
            region: 'Community of Madrid',
            country: 'Spain',
            lat: 40.416775,
            lon: -3.703790,
        },
        description: "Clear your calendar. Let's throw a warm welcome party for the latest dev joining our team. A super talented one that can also make jokes. It'll be fun!",
        sessions: [
            {
                id: 7,
                title: 'Sharing stories session',
                event_start: new Date('2019/10/01 19:00:00').getTime(),
                event_end: new Date('2019/10/01 20:00:00').getTime(),
            },
            {
                id: 8,
                title: 'Beer pong',
                event_start: new Date('2019/10/01 20:00:00').getTime(),
                event_end: new Date('2019/10/01 21:00:00').getTime(),
            },
            {
                id: 10,
                title: 'Pizzas',
                event_start: new Date('2019/10/01 21:00:00').getTime(),
                event_end: new Date('2019/10/01 22:00:00').getTime(),
            },
        ],
    },
    {
        id: 145,
        title: 'Manhattanhenge',
        event_start: new Date('2019/07/13 20:20:00').getTime(),
        event_end: new Date('2019/07/13 20:21:00').getTime(),
        image_url: 'https://d24wuq6o951i2g.cloudfront.net/img/events/splash/front-end-test-manhattan.jpg',
        venue: {
            name: 'Manhattan',
            address: null,
            city: 'New York',
            postalCode: null,
            region: 'NY',
            country: 'United States',
            lat: 40.416775,
            lon: 3.703790,
        },
        description: "Manhattanhenge, also called the Manhattan Solstice, is an event during which the setting sun or the sunrise is aligned with the east–west streets of the main street grid of Manhattan, New York City.",
        sessions: [],
    },
    {
        id: 166,
        title: 'Chinese New Year 🇨🇳',
        event_start: new Date('2019/02/16 00:00:00').getTime(),
        event_end: null,
        image_url: 'https://d24wuq6o951i2g.cloudfront.net/img/events/splash/front-end-test-china.jpg',
        venue: null,
        description: 'Chinese New Year, also known as the "Spring Festival" in modern China, is an important Chinese festival celebrated at the turn of the traditional lunisolar Chinese calendar.',
        sessions: [],
    },
    {
        id: 167,
        title: 'Codemotion Madrid 2019',
        event_start: new Date('2019/11/24 10:00:00').getTime(),
        event_end: new Date('2019/11/25 20:00:00').getTime(),
        image_url: 'https://d24wuq6o951i2g.cloudfront.net/img/events/splash/front-end-test-codemotion.jpg',
        venue: {
            name: null,
            address: null,
            city: 'Madrid',
            postalCode: null,
            region: 'Community of Madrid',
            country: 'Spain',
            lat: 40.416775,
            lon: 3.703790,
        },
        description: "https://2019.codemotion.es/",
        sessions: [
            {
                id: 43,
                title: 'First Day',
                event_start: new Date('2019/11/24 10:00:00').getTime(),
                event_end: new Date('2019/11/24 20:00:00').getTime(),
            },
            {
                id: 45,
                title: 'Second Day',
                event_start: new Date('2019/11/25 10:00:00').getTime(),
                event_end: new Date('2019/11/25 20:00:00').getTime(),
            },
        ],
    },
    {
        id: 212312300,
        title: 'Wedding',
        event_start: new Date('2019/10/25 00:00:00').getTime(),
        event_end: new Date('2019/10/27 00:00:00').getTime(),
        image_url: 'https://urentme.com/app/webroot/img/blog/post_image_1487328910.7849.png',
        venue: {
            name: 'Mike and Julia second Wedding because they are filthy rich',
            address: 'Waldorf Astoria Jerusalem',
            city: 'Jerusalem',
            postalCode: 1029200,
            region: 'Jerusalem',
            country: 'Israel',
            lat: 31.763032,
            lon: 35.205834,
        },
        description: "As we all know Mike is filthy rich and Julia is a gold digger so they decided to marry yet again. As a guest you are expected to get drunk and eat until you puke. PS: The guest of hoomr will be Kanye West. Do not hit on the guy as he will for sure kick your ass!",
        sessions: [
            {
                id: 79,
                title: 'First Day',
                event_start: new Date('2019/10/25 00:00:00').getTime(),
                event_end: null,
            },
            {
                id: 81,
                title: 'Second Day',
                event_start: new Date('2019/11/26 00:00:00').getTime(),
                event_end: null,
            },
            {
                id: 82,
                title: 'Third Day',
                event_start: new Date('2019/11/27 00:00:00').getTime(),
                event_end: null,
            },
        ],
    },
    {
        id: 1012312,
        title: 'Emmy Award 2019',
        event_start: new Date('2019/11/02 10:15:00').getTime(),
        event_end: null,
        image_url: 'https://www.conferencecare.com/files/img-content-event-services-2.jpg',
        venue: {
            name: 'Emmy Awards 2019',
            address: '5 AVE',
            city: 'New York',
            postalCode: 28014,
            region: 'New York Region',
            country: 'New Yrok',
            lat: 40.416775,
            lon: -3.703790,
        },
        description: "You will witness the most amazing event of your life! There will be all the top actors and actresses from all over the world. Free exclusive drinks and exotic food will be served non-stop. Please wear formal clothes like sandals with socks and pejamas with a blazer on top. Disclaimer: do not come naked!",
        sessions: [],
    },
    {
        id: 200,
        title: 'Reactive Conf 2019',
        event_start: new Date('2019/10/25 00:00:00').getTime(),
        event_end: new Date('2019/10/27 00:00:00').getTime(),
        image_url: 'https://d24wuq6o951i2g.cloudfront.net/img/events/splash/front-end-test-react.png',
        venue: {
            name: null,
            address: null,
            city: 'Bratislava',
            postalCode: null,
            region: 'Bratislava',
            country: 'Slovakia',
            lat: null,
            lon: null,
        },
        description: "Discuss the future of development with tech leaders from across the world. Join us on October 25 to 27 in Bratislava, Slovakia. https://reactiveconf.com/",
        sessions: [
            {
                id: 79,
                title: 'First Day',
                event_start: new Date('2019/10/25 00:00:00').getTime(),
                event_end: null,
            },
            {
                id: 81,
                title: 'Second Day',
                event_start: new Date('2019/11/26 00:00:00').getTime(),
                event_end: null,
            },
            {
                id: 82,
                title: 'Third Day',
                event_start: new Date('2019/11/27 00:00:00').getTime(),
                event_end: null,
            },
            {
                id: 83,
                title: 'Extra Workshop: Introduction to Elm',
                event_start: new Date('2019/11/26 10:00:00').getTime(),
                event_end: new Date('2019/11/26 14:00:00').getTime(),
            },
        ],
    },
    {
        id: 10,
        title: 'A talk about coffee',
        event_start: new Date('2019/11/02 10:15:00').getTime(),
        event_end: null,
        image_url: 'https://d24wuq6o951i2g.cloudfront.net/img/events/splash/front-end-test-coffee.jpg',
        venue: {
            name: 'Splash Madrid',
            address: 'Carrera de San Jerónimo 18',
            city: 'Madrid',
            postalCode: 28014,
            region: 'Community of Madrid',
            country: 'Spain',
            lat: 40.416775,
            lon: -3.703790,
        },
        description: "A developer is a wizzard that turns ☕️ into </>. True or false? We'll discuss.",
        sessions: [],
    },
];

exports.events = events;
